frontend/config/routes.rb
Rails.application.routes.draw do
  get 'jobrequests/index'

  get  'api/jobrequest'
  post 'api/jobrequest'

  get  'api/index'
  post 'api/index'

  get  '/login' => 'login#index'
  post '/login' => 'login#index'

  get  '/logout' => 'login#logout'

  get  '/jobrequests/:id/approve', to: 'jobrequests#approve', as: 'jobrequest_approve'
  get  '/jobrequests/:id/disapprove', to: 'jobrequests#disapprove', as: 'jobrequest_disapprove'
  post '/jobrequests/:id/disapprove', to: 'jobrequests#disapprove', as: 'jobrequest_disapprove_post'

  resources :commands, :servers, :jobs, :jobrequests

  root to: 'login#index'

end

frontend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Frontend</title>
  <%= stylesheet_link_tag 'main', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:error] %>
	<div class='error'>
		<%= flash[:error] %>
	</div>
<% end %>
<% if flash[:warning] %>
	<div class='warning'>
		<%= flash[:warning] %>
	</div>
<% end %>
<% if flash[:notice] %>
	<div class='notice'>
		<%= flash[:notice] %>
	</div>
<% end %>

	<% content_for :global_menu do %>
		<div class 
		
	<% end %>

	<div id='menu'>
		<div id='global_menu'>
			<ul>
				<li><%= link_to 'Jobs', jobs_path %></li>
				<li><%= link_to 'Job requests', jobrequests_path %></li>
				<li><%= link_to 'Commands', commands_path %></li>
				<li><%= link_to 'Servers', servers_path %></li>
			</ul>
			<ul>
				<li><%= link_to 'Lydia', Server.find(1) %></li>
				<li><%= link_to 'New job', new_job_path %></li>
			</ul>
		</div>
	</div>
	<div id='content'>
		<%= yield %>
	</div>

</body>
</html>