frontend/config/routes.rb
Rails.application.routes.draw do
  get 'jobrequests/index'

  get  'api/jobrequest'
  post 'api/jobrequest'

  get  'api/index'
  post 'api/index'

  get  '/login' => 'login#index'
  post '/login' => 'login#index'

  get  '/logout' => 'login#logout'

  get  '/jobrequests/:id/approve', to: 'jobrequests#approve', as: 'jobrequest_approve'
  get  '/jobrequests/:id/disapprove', to: 'jobrequests#disapprove', as: 'jobrequest_disapprove'
  post '/jobrequests/:id/disapprove', to: 'jobrequests#disapprove', as: 'jobrequest_disapprove_post'

  resources :commands, :servers, :jobs, :jobrequests

  root to: 'login#index'

end

frontend/app/models/server.rb
class Server < ActiveRecord::Base
	has_many :jobs
	has_many :jobrequests
end

frontend/app/controllers/servers_controller.rb
class ServersController < ApplicationController
	include LoginHelper

	before_action :checkauth
	
	def index
		@servers = Server.all
	end

	def new
	end

	def create
		@server = Server.new(server_params)
		@server.save
		redirect_to @server
	end

	def show
		begin
			@server = Server.find(params[:id])
		rescue => e
			flash[:error] = "No server with that ID."
			redirect_to servers_path
		end

		begin
			@jobcount = @server.jobs.size
		rescue => e
			@jobcount = 0
		end

		begin
			@jobrequestcount = @server.jobrequests.size
		rescue => e
			@jobrequstcount = 0
		end

		begin
			if @jobcount > 0
				@jobs = @server.jobs.order(id: :desc).page(params[:page])
			end
		rescue => e
			flash[:error] = "Could not retrieve server jobs."
			redirect_to servers_path
		end
		
	end

	private
	def server_params
		params.require(:new_server).permit(:shortname, :longname, :localip, :wanip, :description)
	end
end

frontend/app/helpers/servers_helper.rb
module ServersHelper
end

frontend/app/views/servers/index.html.erb
<div class='pagetitle'>
	Servers
</div>
<div class='list'>
	<table>
		<% @servers.each do |server| %>
			<tr>
				<td><%= link_to server.shortname, server %></td>
				<td><%= link_to 'Edit', edit_server_path(server) %></td>
			</tr>
		<% end %>
	</table>
</div>

frontend/app/views/servers/new.html.erb
<div class='pagetitle'>
	New server
</div>
<div class='form'>
	<table>
		<%= form_for :new_server, url: servers_path do |f| %>
			<tr>
				<td>
					<%= f.label :shortname, 'Short name' %>
				</td>
				<td>
					<%= f.text_field :shortname %>
				</td>
			</tr>
			<tr>
				<td>
					<%= f.label :longname, 'Full name (including domain)' %>
				</td>
				<td>
					<%= f.text_field :longname %>
				</td>
			</tr>
			<tr>
				<td>
					<%= f.label :localip, 'Local IP' %>
				</td>
				<td>
					<%= f.text_field :localip %>
				</td>
			</tr>
			<tr>
				<td>
					<%= f.label :wanip, 'WAN IP' %>
				</td>
				<td>
					<%= f.text_field :wanip %>
				</td>
			</tr>
			<tr>
				<td>
					<%= f.label :description, 'Server description' %>
				</td>
				<td>
					<%= f.text_field :description %>
				</td>
			</tr>
			<tr>
				<td>
					<%= f.submit %>
				</td>
			</tr>
		<% end %>
	</table>
</div>

frontend/app/views/servers/show.html.erb
<div class='pagetitle'>
	Server: <%= @server.shortname %>
</div>

<div class='serverdesc'>
	<table>
		<tr>
			<td>Name</td>
			<td><%= @server.shortname %></td>
		</tr>
		<tr>
			<td>FQDN</td>
			<td><%= @server.longname %></td>
		</tr>
		<tr>
			<td>Local IP</td>
			<td><%= @server.localip %></td>
		</tr>
		<tr>
			<td>WAN IP</td>
			<td><%= @server.wanip %></td>
		</tr>
		<tr>
			<td>Description</td>
			<td><%= @server.description %></td>
		</tr>
	</table>
</div>

<div class='newserverjob'>
	<%= link_to 'New job', new_job_path(:server_id => @server.id) %>
</div>

<div class='servertaskspending'>
	<% if @jobrequestcount > 0 %>
		<div class='list'>
			<table>
				<% printheader = true %>
				<% @server.jobrequests.reverse.each do |job| %>
					<% if job.state == 2 %>
					<% if printheader %>
					<tr class='listtitle'>
						<td>Job ID</td>
						<td>User</td>
						<td>E-mail</td>
						<td>Requested</td>
						<td>Processed</td>
						<td>Server</td>
						<td>Command</td>
						<td>Arguments</td>
						<td>Status</td>
					</tr>
					<% printheader = false %>
					<% end %>
					<tr class='jobstatus<%= job.state %>'>
						<td><%= job.id %></td>
						<td><%= job.user %></td>
						<td><%= job.email %></td>
						<td><%= showtime(job.timestampstarted) %></td>
						<td><%= showtime(job.timestampcompleted) %></td>
						<td><%= link_to job.server.shortname, server_path(job.server) %></td>
						<td><%= link_to job.command.name, jobrequest_path(job) %></td>
						<td><%= job.args %></td>
						<td><%= job.result %></td>
					</tr>
					<% end %>
				<% end %>
			</table>
		</div>
	<% else %>
		No job requests on this server.
	<% end %>
</div>

<div class='servertasks'>
	<% if @jobcount > 0 %>
		<div class='list'>
			<table>
					<tr class='listtitle'>
						<td>Job ID</td>
						<td>Started</td>
						<td>Finished</td>
						<td>Command</td>
						<td>Arguments</td>
						<td>Result</td>
					</tr>
				<% @jobs.each do |job| %>
					<tr class='jobstatus<%= job.state %>'>
						<td><%= job.id %></td>
						<td><%= showtime(job.timestampstarted) %></td>
						<td><%= showtime(job.timestampcompleted) %></td>
						<td><%= link_to job.command.name, job_path(job) %></td>
						<td><%= job.args %></td>
						<td><%= job.result %></td>
					</tr>
				<% end %>
			</table>
			<%= paginate @jobs %>
		</div>
	<% else %>
		No jobs on this server.
	<% end %>
</div>