frontend/config/routes.rb
Rails.application.routes.draw do
  get 'jobrequests/index'

  get  'api/jobrequest'
  post 'api/jobrequest'

  get  'api/index'
  post 'api/index'

  get  '/login' => 'login#index'
  post '/login' => 'login#index'

  get  '/logout' => 'login#logout'

  get  '/jobrequests/:id/approve', to: 'jobrequests#approve', as: 'jobrequest_approve'
  get  '/jobrequests/:id/disapprove', to: 'jobrequests#disapprove', as: 'jobrequest_disapprove'
  post '/jobrequests/:id/disapprove', to: 'jobrequests#disapprove', as: 'jobrequest_disapprove_post'

  resources :commands, :servers, :jobs, :jobrequests

  root to: 'login#index'

end

frontend/app/models/jobrequest.rb
class Jobrequest < ActiveRecord::Base
	belongs_to :server
	belongs_to :command
end

frontend/app/controllers/jobrequests_controller.rb
class JobrequestsController < ApplicationController
	include JobsHelper
	include LoginHelper

	before_action :checkauth
	
	def index
		@jobrequests = Jobrequest.all
	end

	def approve
		jr = Jobrequest.find(params[:id])

		# Make job out of request
		@job = Job.new()
		@job.server_id        = jr.server_id
		@job.command_id       = jr.command_id
		@job.args             = "#{jr.user} #{jr.email} #{jr.args}"
		@job.state            = 2
		@job.result           = 'Waiting for results'
		@job.timestampstarted = DateTime.now
		@job.save

		# Update state of request
		jr.state              = 0
		jr.result             = 'Approved'
		jr.timestampcompleted = DateTime.now
		jr.save

		# Fire job into rabbitmq
		queue_job(@job)

		redirect_to @job
	end

	def disapprove
		if params[:disapprove_reason]
			# Update request
			jr = Jobrequest.find(params[:id])
			jr.state  = 1
			jr.result = "Disapproved: #{params[:disapprove_reason][:reason]}"
			jr.timestampcompleted = DateTime.now
			jr.save

			# Send email explaining disapproval
			JobwaitingMailer.jobdisapproved(jr, params[:disapprove_reason][:reason]).deliver

			redirect_to jr
		end
	end

	def show
		begin
			@job = Jobrequest.find(params[:id])
		rescue => e
			flash[:error] = 'No jobrequest with that ID'
			redirect_to jobrequests_path
		end
	end
end

frontend/app/helpers/jobrequests_helper.rb
module JobrequestsHelper
	# List of jobs that do not require admin approval
	# Values of key-value pair are for future use

	def autorun(j)
		autorun_jobs = {
			'httpd_public_html_enable'  => '',
			'httpd_public_html_disable' => '',
			'httpd_cgi-bin_enable'      => '',
			'httpd_chi-bin_disable'     => '',
			'httpd_logs_enable'         => '',
			'httpd_logs_disable'        => '',
			'nanobot_setnick'           => '',
			'twofactor_google_enable'   => '',
			'twofactor_google_disable'  => ''
		}

		return autorun_jobs.has_key? j
	end

	def check_key(key)
		config = loadconfig()
		return config['api_pass'] == key
	end

	def update_job(j)
		if !check_key(j[:key])
			return "Invalid key"
		end

		# Get job
		job = Job.find(j[:id])

		# Update values
		job.timestampcompleted = j[:timestamp]
		job.state              = j[:exitcode]
		job.result             = j[:message]
		job.save
	end
end

frontend/app/views/jobrequests/disapprove.html.erb
<div class='pagetitle'>
	New job
</div>
<div class='form'>
	<table>
		<%= form_for :disapprove_reason, url: jobrequest_disapprove_post_path do |f| %>
			<tr>
				<td>
					<%= f.label :reason, 'Reason for disapproval' %>
				</td>
				<td>
					<%= f.text_field :reason %>
				</td>
			</tr>
			<tr>
				<td>
					<%= f.submit %>
				</td>
			</tr>
		<% end %>
	</table>
</div>

frontend/app/views/jobrequests/index.html.erb
<div class='pagetitle'>
	Job requests
</div>
<div class='list'>
	<table>
			<tr class='listtitle'>
				<td>Job ID</td>
				<td>User</td>
				<td>E-mail</td>
				<td>Requested</td>
				<td>Processed</td>
				<td>Server</td>
				<td>Command</td>
				<td>Arguments</td>
				<td>Status</td>
			</tr>
		<% @jobrequests.reverse.each do |job| %>
			<tr class='jobstatus<%= job.state %>'>
				<td><%= job.id %></td>
				<td><%= job.user %></td>
				<td><%= job.email %></td>
				<td><%= showtime(job.timestampstarted) %></td>
				<td><%= showtime(job.timestampcompleted) %></td>
				<td><%= link_to job.server.shortname, server_path(job.server) %></td>
				<td><%= link_to job.command.name, jobrequest_path(job) %></td>
				<td><%= job.args %></td>
				<td><%= job.result %></td>
			</tr>
		<% end %>
	</table>
</div>

frontend/app/views/jobrequests/show.html.erb
<div class='pagetitle'>
	Jobrequest: <%= @job.id %>
</div>
<div class='form'>
	<table>
		<tr>
			<td>Id</td>
			<td><%= @job.id %></td>
		</tr>
		<tr>
			<td>User</td>
			<td><%= @job.user %></td>
		</tr>
		<tr>
			<td>E-mail address </td>
			<td><%= @job.email %></td>
		</tr>
		<tr>
			<td>Server</td>
			<td><%= @job.server.shortname %></td>
		</tr>
		<tr>
			<td>Command</td>
			<td><%= @job.command.name %></td>
		</tr>
		<tr>
			<td>Arguments</td>
			<td><%= @job.args %></td>
		</tr>
		<tr>
			<td>State id</td>
			<td><%= @job.state %></td>
		</tr>
		<tr>
			<td>Status</td>
			<td><%= @job.result %></td>
		</tr>
		<tr>
			<td>Request time</td>
			<td><%= showtime(@job.timestampstarted) %></td>
		</tr>
		<tr>
			<td>Processed time</td>
			<td><%= showtime(@job.timestampcompleted) %></td>
		</tr>
		<tr>
			<td><%= link_to 'Approve', jobrequest_approve_path %></td>
			<td><%= link_to 'Disapprove', jobrequest_disapprove_path %></td>
		</tr>
	</table>
</div>